### ISSUE TITLE
С чем bem-tools-create-by-css не справляется

### ISSUE THREAD

**Issue by leszeof** [tadatuta/bem-tools-create-by-css#1]
Здравствуйте! 
Во первых, большое спасибо за этот пакет, который решил для меня много вопросов при обучении в Yandex.
Во вторых, к сожалению, при перепаковке проекта игнорируются keyframes и все псевдо-селекторы (ховеры, фокусы, visited, nth-child и подобные). Не проверял только на ::after и ::before (но высока вероятность, что и их не увидит).

Подскажите пожалуйста, можно ли это самостоятельно как то поправить или где можно про это почитать? 

Спасибо за внимание!

**Comment by comrade-amaks** [comment]
Добрый вечер! 
Тоже начал учиться в Яндекс Практикуме, нашел Ваше творение! Спасибо! С первым проектом Kaufman сработало отлично, а на Путешествиях по России, при запуске `npm run start` выдало ошибку.
```bash
$ npm run start

> russian-travels@1.0.0 start
> css-to-bem-file-structure ./pages/index.css

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: Required `entity` field
    at new BemCell (D:\Documents\practicum\projects\russian-travels\node_modules\@bem\cell\index.js:18:9)
    at D:\Documents\practicum\projects\russian-travels\node_modules\bem-tools-create\lib\create.js:102:41
    at Array.map (<anonymous>)
    at D:\Documents\practicum\projects\russian-travels\node_modules\bem-tools-create\lib\create.js:100:61
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

Node.js v18.12.0
```

Конкретно на селекторы не тестировал, но псевдо классы или элементы есть в обоих проектах, keyframes есть в первом(правда не помню если они были прописаны в стилях на момент запуска скрипта... 
Оба проекта есть в моем репо если что. how-to-learn and russian-travels.

**Comment by tadatuta** [comment]
Спасибо за репорты!

Псевдо и прочие сложные селекторы починил в версии `0.0.4`.
А с `keyframes` (как и с переменными, объявленными для `:root`) сложно — не очевидно, в файл к какой именно сущности их положить, поэтому теперь просто кидаю варнинг.
